export const KingMovement = {
  movementOne: { x: 1, y: 0 },
  movementTwo: { x: -1, y: 0 },
  movementThree: { x: 0, y: 1 },
  movementFour: { x: 0, y: -1 },
  movementFive: { x: -1, y: 1 },
  movementSix: { x: -1, y: -1 },
  movementSeven: { x: 1, y: 1 },
  movementEight: { x: 1, y: -1 },
};
export const QueenMovement = {
  moveRight1: { x: 1, y: 0 },
  moveRight2: { x: 2, y: 0 },
  moveRight3: { x: 3, y: 0 },
  moveRight4: { x: 4, y: 0 },
  moveRight5: { x: 5, y: 0 },
  moveRight6: { x: 6, y: 0 },
  moveRight7: { x: 7, y: 0 },

  moveLeft1: { x: -1, y: 0 },
  moveLeft2: { x: -2, y: 0 },
  moveLeft3: { x: -3, y: 0 },
  moveLeft4: { x: -4, y: 0 },
  moveLeft5: { x: -5, y: 0 },
  moveLeft6: { x: -6, y: 0 },
  moveLeft7: { x: -7, y: 0 },

  moveUp1: { x: 0, y: 1 },
  moveUp2: { x: 0, y: 2 },
  moveUp3: { x: 0, y: 3 },
  moveUp4: { x: 0, y: 4 },
  moveUp5: { x: 0, y: 5 },
  moveUp6: { x: 0, y: 6 },
  moveUp7: { x: 0, y: 7 },

  moveDown1: { x: 0, y: -1 },
  moveDown2: { x: 0, y: -2 },
  moveDown3: { x: 0, y: -3 },
  moveDown4: { x: 0, y: -4 },
  moveDown5: { x: 0, y: -5 },
  moveDown6: { x: 0, y: -6 },
  moveDown7: { x: 0, y: -7 },

  moveUpRight1: { x: 1, y: 1 },
  moveUpRight2: { x: 2, y: 2 },
  moveUpRight3: { x: 3, y: 3 },
  moveUpRight4: { x: 4, y: 4 },
  moveUpRight5: { x: 5, y: 5 },
  moveUpRight6: { x: 6, y: 6 },
  moveUpRight7: { x: 7, y: 7 },

  moveUpLeft1: { x: -1, y: 1 },
  moveUpLeft2: { x: -2, y: 2 },
  moveUpLeft3: { x: -3, y: 3 },
  moveUpLeft4: { x: -4, y: 4 },
  moveUpLeft5: { x: -5, y: 5 },
  moveUpLeft6: { x: -6, y: 6 },
  moveUpLeft7: { x: -7, y: 7 },

  moveDownRight1: { x: 1, y: -1 },
  moveDownRight2: { x: 2, y: -2 },
  moveDownRight3: { x: 3, y: -3 },
  moveDownRight4: { x: 4, y: -4 },
  moveDownRight5: { x: 5, y: -5 },
  moveDownRight6: { x: 6, y: -6 },
  moveDownRight7: { x: 7, y: -7 },

  moveDownLeft1: { x: -1, y: -1 },
  moveDownLeft2: { x: -2, y: -2 },
  moveDownLeft3: { x: -3, y: -3 },
  moveDownLeft4: { x: -4, y: -4 },
  moveDownLeft5: { x: -5, y: -5 },
  moveDownLeft6: { x: -6, y: -6 },
  moveDownLeft7: { x: -7, y: -7 },
};
export const RookMovement = {
  moveRightOne: { x: 1, y: 0 },
  moveRightTwo: { x: 2, y: 0 },
  moveRightThree: { x: 3, y: 0 },
  moveRightFour: { x: 4, y: 0 },
  moveRightFive: { x: 5, y: 0 },
  moveRightSix: { x: 6, y: 0 },
  moveRightSeven: { x: 7, y: 0 },
  moveLeftOne: { x: -1, y: 0 },
  moveLeftTwo: { x: -2, y: 0 },
  moveLeftThree: { x: -3, y: 0 },
  moveLeftFour: { x: -4, y: 0 },
  moveLeftFive: { x: -5, y: 0 },
  moveLeftSix: { x: -6, y: 0 },
  moveLeftSeven: { x: -7, y: 0 },
  moveUpOne: { x: 0, y: 1 },
  moveUpTwo: { x: 0, y: 2 },
  moveUpThree: { x: 0, y: 3 },
  moveUpFour: { x: 0, y: 4 },
  moveUpFive: { x: 0, y: 5 },
  moveUpSix: { x: 0, y: 6 },
  moveUpSeven: { x: 0, y: 7 },
  moveDownOne: { x: 0, y: -1 },
  moveDownTwo: { x: 0, y: -2 },
  moveDownThree: { x: 0, y: -3 },
  moveDownFour: { x: 0, y: -4 },
  moveDownFive: { x: 0, y: -5 },
  moveDownSix: { x: 0, y: -6 },
  moveDownSeven: { x: 0, y: -7 },
};
export const HorseMovement = [
  { x: 2, y: 1 },
  { x: 2, y: -1 },
  { x: -2, y: 1 },
  { x: -2, y: -1 },
  { x: 1, y: 2 },
  { x: 1, y: -2 },
  { x: -1, y: 2 },
  { x: -1, y: -2 },
];

export const CamelMovement = [
  { x: -1, y: -1 },
  { x: -2, y: -2 },
  { x: -3, y: -3 },
  { x: -4, y: -4 },
  { x: -5, y: -5 },
  { x: -6, y: -6 },
  { x: -7, y: -7 },

  { x: -1, y: 1 },
  { x: -2, y: 2 },
  { x: -3, y: 3 },
  { x: -4, y: 4 },
  { x: -5, y: 5 },
  { x: -6, y: 6 },
  { x: -7, y: 7 },

  { x: 1, y: -1 },
  { x: 2, y: -2 },
  { x: 3, y: -3 },
  { x: 4, y: -4 },
  { x: 5, y: -5 },
  { x: 6, y: -6 },
  { x: 7, y: -7 },

  { x: 1, y: 1 },
  { x: 2, y: 2 },
  { x: 3, y: 3 },
  { x: 4, y: 4 },
  { x: 5, y: 5 },
  { x: 6, y: 6 },
  { x: 7, y: 7 },
];
export const PawnMovement = {
  moveForward: { x: -1, y: 0 },
  doubleMove: { x: -2, y: 0 },
  captureLeft: { x: -1, y: -1 },
  captureRight: { x: -1, y: 1 },
};
export const BlackKingMovement = {
  movementOne: { x: 1, y: 0 },
  movementTwo: { x: -1, y: 0 },
  movementThree: { x: 0, y: 1 },
  movementFour: { x: 0, y: -1 },
  movementFive: { x: -1, y: 1 },
  movementSix: { x: -1, y: -1 },
  movementSeven: { x: 1, y: 1 },
  movementEight: { x: 1, y: -1 },
};

export const BlackQueenMovement = {
  moveRight1: { x: 1, y: 0 },
  moveRight2: { x: 2, y: 0 },
  moveRight3: { x: 3, y: 0 },
  moveRight4: { x: 4, y: 0 },
  moveRight5: { x: 5, y: 0 },
  moveRight6: { x: 6, y: 0 },
  moveRight7: { x: 7, y: 0 },

  moveLeft1: { x: -1, y: 0 },
  moveLeft2: { x: -2, y: 0 },
  moveLeft3: { x: -3, y: 0 },
  moveLeft4: { x: -4, y: 0 },
  moveLeft5: { x: -5, y: 0 },
  moveLeft6: { x: -6, y: 0 },
  moveLeft7: { x: -7, y: 0 },

  moveUp1: { x: 0, y: -1 },
  moveUp2: { x: 0, y: -2 },
  moveUp3: { x: 0, y: -3 },
  moveUp4: { x: 0, y: -4 },
  moveUp5: { x: 0, y: -5 },
  moveUp6: { x: 0, y: -6 },
  moveUp7: { x: 0, y: -7 },

  moveDown1: { x: 0, y: 1 },
  moveDown2: { x: 0, y: 2 },
  moveDown3: { x: 0, y: 3 },
  moveDown4: { x: 0, y: 4 },
  moveDown5: { x: 0, y: 5 },
  moveDown6: { x: 0, y: 6 },
  moveDown7: { x: 0, y: 7 },

  moveUpRight1: { x: 1, y: -1 },
  moveUpRight2: { x: 2, y: -2 },
  moveUpRight3: { x: 3, y: -3 },
  moveUpRight4: { x: 4, y: -4 },
  moveUpRight5: { x: 5, y: -5 },
  moveUpRight6: { x: 6, y: -6 },
  moveUpRight7: { x: 7, y: -7 },

  moveUpLeft1: { x: -1, y: -1 },
  moveUpLeft2: { x: -2, y: -2 },
  moveUpLeft3: { x: -3, y: -3 },
  moveUpLeft4: { x: -4, y: -4 },
  moveUpLeft5: { x: -5, y: -5 },
  moveUpLeft6: { x: -6, y: -6 },
  moveUpLeft7: { x: -7, y: -7 },

  moveDownRight1: { x: 1, y: 1 },
  moveDownRight2: { x: 2, y: 2 },
  moveDownRight3: { x: 3, y: 3 },
  moveDownRight4: { x: 4, y: 4 },
  moveDownRight5: { x: 5, y: 5 },
  moveDownRight6: { x: 6, y: 6 },
  moveDownRight7: { x: 7, y: 7 },

  moveDownLeft1: { x: -1, y: 1 },
  moveDownLeft2: { x: -2, y: 2 },
  moveDownLeft3: { x: -3, y: 3 },
  moveDownLeft4: { x: -4, y: 4 },
  moveDownLeft5: { x: -5, y: 5 },
  moveDownLeft6: { x: -6, y: 6 },
  moveDownLeft7: { x: -7, y: 7 },
};

export const BlackRookMovement = {
  moveRightOne: { x: 1, y: 0 },
  moveRightTwo: { x: 2, y: 0 },
  moveRightThree: { x: 3, y: 0 },
  moveRightFour: { x: 4, y: 0 },
  moveRightFive: { x: 5, y: 0 },
  moveRightSix: { x: 6, y: 0 },
  moveRightSeven: { x: 7, y: 0 },

  moveLeftOne: { x: -1, y: 0 },
  moveLeftTwo: { x: -2, y: 0 },
  moveLeftThree: { x: -3, y: 0 },
  moveLeftFour: { x: -4, y: 0 },
  moveLeftFive: { x: -5, y: 0 },
  moveLeftSix: { x: -6, y: 0 },
  moveLeftSeven: { x: -7, y: 0 },

  moveUpOne: { x: 0, y: -1 },
  moveUpTwo: { x: 0, y: -2 },
  moveUpThree: { x: 0, y: -3 },
  moveUpFour: { x: 0, y: -4 },
  moveUpFive: { x: 0, y: -5 },
  moveUpSix: { x: 0, y: -6 },
  moveUpSeven: { x: 0, y: -7 },

  moveDownOne: { x: 0, y: 1 },
  moveDownTwo: { x: 0, y: 2 },
  moveDownThree: { x: 0, y: 3 },
  moveDownFour: { x: 0, y: 4 },
  moveDownFive: { x: 0, y: 5 },
  moveDownSix: { x: 0, y: 6 },
  moveDownSeven: { x: 0, y: 7 },
};

export const BlackHorseMovement = [
  { x: 2, y: 1 },
  { x: 2, y: -1 },
  { x: -2, y: 1 },
  { x: -2, y: -1 },
  { x: 1, y: 2 },
  { x: 1, y: -2 },
  { x: -1, y: 2 },
  { x: -1, y: -2 },
];

export const BlackCamelMovement = [
  { x: -1, y: -1 },
  { x: -2, y: -2 },
  { x: -3, y: -3 },
  { x: -4, y: -4 },
  { x: -5, y: -5 },
  { x: -6, y: -6 },
  { x: -7, y: -7 },

  { x: -1, y: 1 },
  { x: -2, y: 2 },
  { x: -3, y: 3 },
  { x: -4, y: 4 },
  { x: -5, y: 5 },
  { x: -6, y: 6 },
  { x: -7, y: 7 },

  { x: 1, y: -1 },
  { x: 2, y: -2 },
  { x: 3, y: -3 },
  { x: 4, y: -4 },
  { x: 5, y: -5 },
  { x: 6, y: -6 },
  { x: 7, y: -7 },

  { x: 1, y: 1 },
  { x: 2, y: 2 },
  { x: 3, y: 3 },
  { x: 4, y: 4 },
  { x: 5, y: 5 },
  { x: 6, y: 6 },
  { x: 7, y: 7 },
];

export const BlackPawnMovement = {
  moveForward: { x: 1, y: 0 },
  doubleMove: { x: 2, y: 0 },
  captureLeft: { x: 1, y: -1 },
  captureRight: { x: 1, y: 1 },
};
